//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGAC.Layers.Bussiness.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTIVOS
    {
        public int ID { get; set; }
        public string CODIGO { get; set; }
        public string SERIAL { get; set; }
        public string DESCRIPCION { get; set; }
        public byte[] DETALLE { get; set; }
        public string MARCA { get; set; }
        public string MODELO { get; set; }
        public string LOCALIZACION { get; set; }
        public byte[] OBSERVACION { get; set; }
        public Nullable<decimal> MONTO_AQUISICION { get; set; }
        public Nullable<decimal> MONTO_RETIRO { get; set; }
        public Nullable<decimal> MONTO_AVALUO { get; set; }
        public Nullable<decimal> MONTO_AJUSTADO { get; set; }
        public Nullable<decimal> MONTO_DESPRECIACION { get; set; }
        public Nullable<decimal> MONTO_TRANFERENCIA { get; set; }
        public Nullable<int> VIDA_UTIL { get; set; }
        public Nullable<int> EDAD_MESES { get; set; }
        public Nullable<int> VIDA_REMANENTE { get; set; }
        public Nullable<System.DateTime> FECHA_ADQUISICION { get; set; }
        public Nullable<System.DateTime> FECHA_CADUCIDAD { get; set; }
        public Nullable<int> PROVEEDOR { get; set; }
        public string ORDEN { get; set; }
        public string DOCUMENTO_PROV { get; set; }
        public string TIPO { get; set; }
        public string DOCUMENTO_PN { get; set; }
        public Nullable<int> TIPO_ACTIVO { get; set; }
        public string ESTATUS { get; set; }
        public string OTROS { get; set; }
        public Nullable<int> DATOS { get; set; }
        public Nullable<int> ID_ESCUELA { get; set; }
    }
}
