//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGAC.Layers.Bussiness.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASIGNATURAS
    {
        public decimal ID { get; set; }
        public decimal CURSOS { get; set; }
        public string NOMBRE { get; set; }
        public byte[] DESCRIPCION { get; set; }
        public byte[] CONTENIDO { get; set; }
        public byte[] OBSERVACION { get; set; }
        public Nullable<decimal> HORAS { get; set; }
        public Nullable<System.DateTime> FECHA_INICIO { get; set; }
        public Nullable<System.DateTime> FECHA_FIN { get; set; }
        public Nullable<decimal> CREDITOS { get; set; }
        public Nullable<decimal> CAMPO1 { get; set; }
        public Nullable<decimal> CAMPO2 { get; set; }
        public string CAMPO3 { get; set; }
        public string ESTATUS { get; set; }
        public string HORARIO1 { get; set; }
        public string HORARIO2 { get; set; }
        public Nullable<decimal> HORA1 { get; set; }
        public Nullable<decimal> HORA2 { get; set; }
        public Nullable<decimal> TIPO { get; set; }
    }
}
