//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGAC.Layers.Bussiness.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AULAS_ACTIVOS
    {
        public int ID { get; set; }
        public int ID_AULA { get; set; }
        public string CODIGO { get; set; }
        public string SERIAL { get; set; }
        public string DESCRIPCION { get; set; }
        public byte[] DETALLE { get; set; }
        public System.DateTime FECHA { get; set; }
        public Nullable<long> ASIGNADO { get; set; }
        public string ESTATUS { get; set; }
        public string DATOS1 { get; set; }
        public string DATOS2 { get; set; }
        public Nullable<int> DATOS3 { get; set; }
    }
}
