//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGAC.Layers.Bussiness.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AULAS
    {
        public decimal ID { get; set; }
        public string AULA { get; set; }
        public string UBICACION { get; set; }
        public byte[] DESCRIPCION { get; set; }
        public string NOTA { get; set; }
        public decimal RECINTO { get; set; }
        public decimal ESCUELA { get; set; }
    }
}
