//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGAC.Layers.Bussiness.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESCUELA
    {
        public decimal ID { get; set; }
        public decimal ID_RECINTO { get; set; }
        public string NOMBRE { get; set; }
        public byte[] DESCRIPCION { get; set; }
        public byte[] NOTA { get; set; }
        public string TELEFONO { get; set; }
        public string TELEFONO2 { get; set; }
        public string EMAIL { get; set; }
        public string RESPONSABLE { get; set; }
        public string ESTATUS { get; set; }
    }
}
