//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGAC.Layers.Bussiness.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOVIMIENTO_PERSONAL
    {
        public int ID { get; set; }
        public long CEDULA { get; set; }
        public int ID_RECINTO { get; set; }
        public int ID_AULA { get; set; }
        public int ID_ASIGNATURA { get; set; }
        public string HORARIOS { get; set; }
        public System.DateTime FECHA { get; set; }
        public string DATOS1 { get; set; }
        public string DATOS2 { get; set; }
        public string DATOS3 { get; set; }
        public Nullable<int> DATOS4 { get; set; }
        public Nullable<int> DATOS5 { get; set; }
    }
}
