//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGAC.Layers.Bussiness.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROVEEDOR
    {
        public int ID { get; set; }
        public string NOMBRE { get; set; }
        public string DESCRIPCION { get; set; }
        public string DIRECCION { get; set; }
        public Nullable<int> TIPO { get; set; }
        public string TELEFONOS { get; set; }
        public string EMAIL { get; set; }
        public Nullable<long> RNC { get; set; }
        public byte[] ACTIVIDADES { get; set; }
        public byte[] NOTA { get; set; }
        public Nullable<bool> ESTATUS { get; set; }
    }
}
