//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGAC.Layers.Bussiness.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIEDU_PRESUPUESTO
    {
        public int PPTO_PPTO { get; set; }
        public int PPTO_CAPA { get; set; }
        public string PPTO_NRO_CONTRA { get; set; }
        public decimal PPTO_VLR_CONTRA { get; set; }
        public Nullable<System.DateTime> PPTO_FECHA_CONTRA { get; set; }
        public Nullable<short> PPTO_DOM_RECU { get; set; }
        public string PPTO_ORIGEN { get; set; }
        public string PPTO_USU_CREA { get; set; }
        public System.DateTime PPTO_FECHA_CREA { get; set; }
        public string PPTO_MAQUINA_CREA { get; set; }
        public string PPTO_IP_CREA { get; set; }
        public string PPTO_USU_MOD { get; set; }
        public Nullable<System.DateTime> PPTO_FECHA_MOD { get; set; }
        public string PPTO_MAQUINA_MOD { get; set; }
        public string PPTO_IP_MOD { get; set; }
    
        public virtual SIEDU_PAE_CAPACITACION SIEDU_PAE_CAPACITACION { get; set; }
    }
}
