//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGAC.Layers.Bussiness.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIEDU_COBERTURA
    {
        public int COBE_COBE { get; set; }
        public int COBE_PAE { get; set; }
        public bool COBE_UDE_FUERZA_UFISI { get; set; }
        public decimal COBE_UDE_UFISI { get; set; }
        public short COBE_DOM_ESTRA { get; set; }
        public bool COBE_UDE_FUERZA_ESCU { get; set; }
        public decimal COBE_UDE_ESCU { get; set; }
        public string COBE_USU_CREA { get; set; }
        public System.DateTime COBE_FECHA_CREA { get; set; }
        public string COBE_MAQUINA_CREA { get; set; }
        public string COBE_IP_CREA { get; set; }
        public string COBE_USU_MOD { get; set; }
        public Nullable<System.DateTime> COBE_FECHA_MOD { get; set; }
        public string COBE_MAQUINA_MOD { get; set; }
        public string COBE_IP_MOD { get; set; }
    }
}
