//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGAC.Layers.Bussiness.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIEDU_CONVENIO
    {
        public short CONV_CONV { get; set; }
        public string CONV_NOMBRE { get; set; }
        public string CONV_DESCRI { get; set; }
        public short CONVE_DOM_CONV { get; set; }
        public decimal CONVE_ENTI { get; set; }
        public Nullable<System.DateTime> CONV_FECHA_INI { get; set; }
        public Nullable<System.DateTime> CONV_FECHA_FIN { get; set; }
        public string CONV_VIGENTE { get; set; }
        public string CONV_USU_CREA { get; set; }
        public System.DateTime CONV_FECHA_CREA { get; set; }
        public string CONV_MAQUINA_CREA { get; set; }
        public string CONV_IP_CREA { get; set; }
        public string CONV_USU_MOD { get; set; }
        public Nullable<System.DateTime> CONV_FECHA_MOD { get; set; }
        public string CONV_MAQUINA_MOD { get; set; }
        public string CONV_IP_MOD { get; set; }
    
        public virtual SIEDU_ENTIDAD SIEDU_ENTIDAD { get; set; }
    }
}
