//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGAC.Layers.Bussiness.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIEDU_PAE_FORMA_ESCUELA
    {
        public int FRME_FORM { get; set; }
        public bool FRME_UDE_FUERZA { get; set; }
        public decimal FRME_UDE_ESCU { get; set; }
        public string FRMS_USU_CREA { get; set; }
        public System.DateTime FRMS_FECHA_CREA { get; set; }
        public string FRMS_MAQUINA_CREA { get; set; }
        public string FRMS_IP_CREA { get; set; }
        public string FRMS_USU_MOD { get; set; }
        public Nullable<System.DateTime> FRMS_FECHA_MOD { get; set; }
        public string FRMS_MAQUINA_MOD { get; set; }
        public string FRMS_IP_MOD { get; set; }
    
        public virtual SIEDU_PAE_FORMACION SIEDU_PAE_FORMACION { get; set; }
    }
}
