//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGAC.Layers.Bussiness.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIEDU_PAE
    {
        public int PAE_PAE { get; set; }
        public string PAE_VIGENCIA { get; set; }
        public string PAE_ESTADO { get; set; }
        public string PAE_NECE_YA_IMPORTADA { get; set; }
        public string PAE_USU_CREA { get; set; }
        public System.DateTime PAE_FECHA_CREA { get; set; }
        public string PAE_MAQUINA_CREA { get; set; }
        public string PAE_IP_CREA { get; set; }
        public string PAE_USU_MOD { get; set; }
        public Nullable<System.DateTime> PAE_FECHA_MOD { get; set; }
        public string PAE_MAQUINA_MOD { get; set; }
        public string PAE_IP_MOD { get; set; }
    }
}
