//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGAC.Layers.Bussiness.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIEDU_ENTIDAD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SIEDU_ENTIDAD()
        {
            this.SIEDU_CONVENIO = new HashSet<SIEDU_CONVENIO>();
        }
    
        public decimal ENTI_ENTI { get; set; }
        public string ENTI_NOMBRE { get; set; }
        public short ENTI_DOM_TIPO { get; set; }
        public int ENTI_LUGGEO { get; set; }
        public short ENTI_DOM_SECTOR { get; set; }
        public string ENTI_DIRECCION { get; set; }
        public Nullable<decimal> ENTI_TELEFONO { get; set; }
        public string ENTI_PAGE_WEB { get; set; }
        public string ENTI_EMAIL { get; set; }
        public string ENTI_USU_CREA { get; set; }
        public System.DateTime ENTI_FECHA_CREA { get; set; }
        public string ENTI_MAQUINA_CREA { get; set; }
        public string ENTI_IP_CREA { get; set; }
        public string ENTI_USU_MOD { get; set; }
        public Nullable<System.DateTime> ENTI_FECHA_MOD { get; set; }
        public string ENTI_MAQUINA_MOD { get; set; }
        public string ENTI_IP_MOD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIEDU_CONVENIO> SIEDU_CONVENIO { get; set; }
    }
}
