//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGAC.Layers.Bussiness.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIEDU_EVENTO_CATEGORIA
    {
        public int EVCA_EVCA { get; set; }
        public int EVCA_EVEN { get; set; }
        public bool EVCA_FUERZA { get; set; }
        public decimal EVCA_CATEGORIA_ID { get; set; }
        public byte EVCA_ORDEN { get; set; }
        public string EVCA_USU_CREA { get; set; }
        public System.DateTime EVCA_FECHA_CREA { get; set; }
        public string EVCA_MAQUINA_CREA { get; set; }
        public string EVCA_IP_CREA { get; set; }
        public string EVCA_USU_MOD { get; set; }
        public Nullable<System.DateTime> EVCA_FECHA_MOD { get; set; }
        public string EVCA_MAQUINA_MOD { get; set; }
        public string EVCA_IP_MOD { get; set; }
    }
}
