//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGAC.Layers.Bussiness.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIEDU_ARCHIVO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SIEDU_ARCHIVO()
        {
            this.SIEDU_NOVEDAD_PAE = new HashSet<SIEDU_NOVEDAD_PAE>();
        }
    
        public int ARCH_ID { get; set; }
        public string ARCH_NOMBRE { get; set; }
        public string ARCH_EXT { get; set; }
        public string ARCH_CONTENT_TYPE { get; set; }
        public string ARCH_TITULO { get; set; }
        public string ARCH_USU_CREA { get; set; }
        public System.DateTime ARCH_FECHA_CREA { get; set; }
        public string ARCH_MAQUINA_CREA { get; set; }
        public string ARCH_IP_CREA { get; set; }
        public string ARCH_USU_MOD { get; set; }
        public Nullable<System.DateTime> ARCH_FECHA_MOD { get; set; }
        public string ARCH_MAQUINA_MOD { get; set; }
        public string ARCH_IP_MOD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIEDU_NOVEDAD_PAE> SIEDU_NOVEDAD_PAE { get; set; }
    }
}
