//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGAC.Layers.Bussiness.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIEDU_CONSOLIDA_PAE
    {
        public int CPAE_CPAE { get; set; }
        public int CPAE_NECE { get; set; }
        public Nullable<int> CPAE_CAPA { get; set; }
        public Nullable<int> CPAE_FORM { get; set; }
        public string CPAE_USU_CREA { get; set; }
        public System.DateTime CPAE_FECHA_CREA { get; set; }
        public string CPAE_MAQUINA_CREA { get; set; }
        public string CPAE_IP_CREA { get; set; }
        public string CPAE_USU_MOD { get; set; }
        public Nullable<System.DateTime> CPAE_FECHA_MOD { get; set; }
        public string CPAE_MAQUINA_MOD { get; set; }
        public string CPAE_IP_MOD { get; set; }
    }
}
