//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGAC.Layers.Bussiness.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIEDU_PERSONA
    {
        public int PERS_PERS { get; set; }
        public string PERS_NROID { get; set; }
        public Nullable<short> PERS_TPOID { get; set; }
        public string PERS_NOMBRES { get; set; }
        public string PERS_APELLIDOS { get; set; }
        public Nullable<int> PERS_EMPE { get; set; }
        public Nullable<bool> PERS_EMP_UNDE_FUERZA { get; set; }
        public Nullable<decimal> PERS_EMP_UNDE_UDEPE { get; set; }
        public Nullable<decimal> PERS_EMP_CONSECUTIVO { get; set; }
        public string PERS_USU_CREA { get; set; }
        public System.DateTime PERS_FECHA_CREA { get; set; }
        public string PERS_MAQUINA_CREA { get; set; }
        public string PERS_IP_CREA { get; set; }
        public string PERS_USU_MOD { get; set; }
        public Nullable<System.DateTime> PERS_FECHA_MOD { get; set; }
        public string PERS_MAQUINA_MOD { get; set; }
        public string PERS_IP_MOD { get; set; }
    }
}
