//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGAC.Layers.Bussiness.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIEDU_DOCENTE_EVENTO
    {
        public int DOCE_DOCE { get; set; }
        public int DOCE_EVEE { get; set; }
        public int DOCE_TEMA { get; set; }
        public int DOCE_PERS { get; set; }
        public string DOCE_USU_CREA { get; set; }
        public System.DateTime DOCE_FECHA_CREA { get; set; }
        public string DOCE_MAQUINA_CREA { get; set; }
        public string DOCE_IP_CREA { get; set; }
        public string DOCE_USU_MOD { get; set; }
        public Nullable<System.DateTime> DOCE_FECHA_MOD { get; set; }
        public string DOCE_MAQUINA_MOD { get; set; }
        public string DOCE_IP_MOD { get; set; }
    }
}
