//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGAC.Layers.Bussiness.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIEDU_PAE_FORMACION
    {
        public int FORM_FORM { get; set; }
        public int FORM_PAE { get; set; }
        public Nullable<short> FORM_DOM_PROCE { get; set; }
        public Nullable<short> FORM_DOM_ESTRA { get; set; }
        public Nullable<int> FORM_NECESI { get; set; }
        public string FORM_ESTADO { get; set; }
        public bool FORM_FUERZA { get; set; }
        public decimal FORM_ID_CARRERA { get; set; }
        public string FORM_USU_CREA { get; set; }
        public System.DateTime FORM_FECHA_CREA { get; set; }
        public string FORM_MAQUINA_CREA { get; set; }
        public string FORM_IP_CREA { get; set; }
        public string FORM_USU_MOD { get; set; }
        public Nullable<System.DateTime> FORM_FECHA_MOD { get; set; }
        public string FORM_MAQUINA_MOD { get; set; }
        public string FORM_IP_MOD { get; set; }
    }
}
