//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGAC.Layers.Bussiness.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIEDU_NECESIDAD_E
    {
        public int ENEC_ENEC { get; set; }
        public string ENEC_VIGENCIA { get; set; }
        public bool ENEC_UDE_FUERZA_REGION { get; set; }
        public decimal ENEC_UDE_REGION { get; set; }
        public bool ENEC_UDE_FUERZA_UFISI { get; set; }
        public decimal ENEC_UDE_UFISI { get; set; }
        public bool ENEC_UDE_FUERZA_UDEPE { get; set; }
        public decimal ENEC_UDE_UDEPE { get; set; }
        public bool ENEC_FUERZA_CARRERA { get; set; }
        public decimal ENEC_ID_CARRERA { get; set; }
        public string ENEC_ORIGEN { get; set; }
        public int ENEC_NRO { get; set; }
        public string ENEC_ENVIADO { get; set; }
    }
}
