//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGAC.Layers.Bussiness.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIEDU_TEMA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SIEDU_TEMA()
        {
            this.SIEDU_TEMA1 = new HashSet<SIEDU_TEMA>();
        }
    
        public int TEMA_TEMA { get; set; }
        public int TEMA_EVEN { get; set; }
        public byte TEMA_ORDEN { get; set; }
        public string TEMA_DESCRI { get; set; }
        public short TEMA_HORAS { get; set; }
        public Nullable<short> TEMA_DOM_TEMATICA { get; set; }
        public Nullable<int> TEMA_TEMA_PADRE { get; set; }
        public string TEMA_USU_CREA { get; set; }
        public System.DateTime TEMA_FECHA_CREA { get; set; }
        public string TEMA_MAQUINA_CREA { get; set; }
        public string TEMA_IP_CREA { get; set; }
        public string TEMA_USU_MOD { get; set; }
        public Nullable<System.DateTime> TEMA_FECHA_MOD { get; set; }
        public string TEMA_MAQUINA_MOD { get; set; }
        public string TEMA_IP_MOD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIEDU_TEMA> SIEDU_TEMA1 { get; set; }
        public virtual SIEDU_TEMA SIEDU_TEMA2 { get; set; }
    }
}
