//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGAC.Layers.Bussiness.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIEDU_PAE_FORMACION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SIEDU_PAE_FORMACION()
        {
            this.SIEDU_PAE_FORMA_ESCUELA = new HashSet<SIEDU_PAE_FORMA_ESCUELA>();
        }
    
        public int FORM_FORM { get; set; }
        public int FORM_PAE { get; set; }
        public Nullable<short> FORM_DOM_PROCE { get; set; }
        public Nullable<short> FORM_DOM_ESTRA { get; set; }
        public Nullable<int> FORM_NECESI { get; set; }
        public string FORM_ESTADO { get; set; }
        public bool FORM_FUERZA { get; set; }
        public decimal FORM_ID_CARRERA { get; set; }
        public string FORM_USU_CREA { get; set; }
        public System.DateTime FORM_FECHA_CREA { get; set; }
        public string FORM_MAQUINA_CREA { get; set; }
        public string FORM_IP_CREA { get; set; }
        public string FORM_USU_MOD { get; set; }
        public Nullable<System.DateTime> FORM_FECHA_MOD { get; set; }
        public string FORM_MAQUINA_MOD { get; set; }
        public string FORM_IP_MOD { get; set; }
    
        public virtual SIEDU_PAE SIEDU_PAE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIEDU_PAE_FORMA_ESCUELA> SIEDU_PAE_FORMA_ESCUELA { get; set; }
    }
}
