//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGAC.Layers.Bussiness.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIEDU_FORMA_ESCUELA_COHORTE
    {
        public int FREH_FORM { get; set; }
        public bool FREH_FUERZA { get; set; }
        public decimal FREH_ESCU { get; set; }
        public byte FREH_COHO { get; set; }
        public Nullable<short> FREH_COHO_CONSECU { get; set; }
        public System.DateTime FREH_FECHA_INI { get; set; }
        public System.DateTime FREH_FECHA_FIN { get; set; }
        public Nullable<short> FREH_NRO_ESTU { get; set; }
        public Nullable<short> FREH_DOM_MODAL { get; set; }
        public string FREH_USU_CREA { get; set; }
        public System.DateTime FREH_FECHA_CREA { get; set; }
        public string FREH_MAQUINA_CREA { get; set; }
        public string FREH_IP_CREA { get; set; }
        public string FREH_USU_MOD { get; set; }
        public Nullable<System.DateTime> FREH_FECHA_MOD { get; set; }
        public string FREH_MAQUINA_MOD { get; set; }
        public string FREH_IP_MOD { get; set; }
    }
}
