//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGAC.Layers.Bussiness.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIEDU_CONVOCATORIA_EVENTO
    {
        public int CONE_CONE { get; set; }
        public int CONE_EVEE { get; set; }
        public bool CONE_UDE_FUERZA { get; set; }
        public decimal CONE_UDE_UDEPE { get; set; }
        public Nullable<short> CONE_DOM_TPCOMU { get; set; }
        public string CONE_NRO_COMU { get; set; }
        public Nullable<int> CONE_NRO_CONVOCADOS { get; set; }
        public Nullable<int> CONE_NRO_PRESENTADOS { get; set; }
        public string CONE_USU_CREA { get; set; }
        public System.DateTime CONE_FECHA_CREA { get; set; }
        public string CONE_MAQUINA_CREA { get; set; }
        public string CONE_IP_CREA { get; set; }
        public string CONE_USU_MOD { get; set; }
        public Nullable<System.DateTime> CONE_FECHA_MOD { get; set; }
        public string CONE_MAQUINA_MOD { get; set; }
        public string CONE_IP_MOD { get; set; }
    }
}
