//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGAC.Layers.Bussiness.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIEDU_COMPETENCIA_EVENTO
    {
        public int COMPE_EVEN { get; set; }
        public short COMPE_COMP { get; set; }
        public byte COMPE_ORDEN { get; set; }
        public string COMPE_USU_CREA { get; set; }
        public System.DateTime COMPE_FECHA_CREA { get; set; }
        public string COMPE_MAQUINA_CREA { get; set; }
        public string COMPE_IP_CREA { get; set; }
        public string COMPE_USU_MOD { get; set; }
        public Nullable<System.DateTime> COMPE_FECHA_MOD { get; set; }
        public string COMPE_MAQUINA_MOD { get; set; }
        public string COMPE_IP_MOD { get; set; }
    }
}
