//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGAC.Layers.Bussiness.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIEDU_EVENTO
    {
        public int EVEN_EVEN { get; set; }
        public short EVEN_DOM_MODAL { get; set; }
        public short EVEN_DOM_PROCE { get; set; }
        public bool EVEN_FUERZA { get; set; }
        public decimal EVEN_ID_CARRERA { get; set; }
        public string EVEN_JUSTIFICA { get; set; }
        public string EVEN_OBJE_GRAL { get; set; }
        public string EVEN_OBJE_ESPE { get; set; }
        public string EVEN_DIRIGIDOA { get; set; }
        public short EVEN_INTEN_HORAS { get; set; }
        public System.DateTime EVEN_FECHA_VER { get; set; }
        public string EVEN_ESTADO { get; set; }
        public string EVEN_USU_CREA { get; set; }
        public System.DateTime EVEN_FECHA_CREA { get; set; }
        public string EVEN_MAQUINA_CREA { get; set; }
        public string EVEN_IP_CREA { get; set; }
        public string EVEN_USU_MOD { get; set; }
        public Nullable<System.DateTime> EVEN_FECHA_MOD { get; set; }
        public string EVEN_MAQUINA_MOD { get; set; }
        public string EVEN_IP_MOD { get; set; }
    }
}
