//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGAC.Layers.Bussiness.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIEDU_NOVEDAD_PAE
    {
        public short NOVE_NOVE { get; set; }
        public int NOVE_PAE { get; set; }
        public System.DateTime NOVE_FECHA { get; set; }
        public string NOVE_PROCEDI { get; set; }
        public string NOVE_TPO_DOC { get; set; }
        public string NOVE_NRO_DOC { get; set; }
        public System.DateTime NOVE_FECHA_DOC { get; set; }
        public string NOVE_OBSERVA { get; set; }
        public Nullable<int> NOVE_ANEXO_PDF { get; set; }
        public string NOVE_USU_CREA { get; set; }
        public System.DateTime NOVE_FECHA_CREA { get; set; }
        public string NOVE_MAQUINA_CREA { get; set; }
        public string NOVE_IP_CREA { get; set; }
        public string NOVE_USU_MOD { get; set; }
        public Nullable<System.DateTime> NOVE_FECHA_MOD { get; set; }
        public string NOVE_MAQUINA_MOD { get; set; }
        public string NOVE_IP_MOD { get; set; }
    
        public virtual SIEDU_ARCHIVO SIEDU_ARCHIVO { get; set; }
        public virtual SIEDU_PAE SIEDU_PAE { get; set; }
    }
}
