//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGAC.Layers.Bussiness.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIEDU_EVALUACION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SIEDU_EVALUACION()
        {
            this.SIEDU_EVENTO_ESCUELA = new HashSet<SIEDU_EVENTO_ESCUELA>();
            this.SIEDU_EVAL_CATEGORIA = new HashSet<SIEDU_EVAL_CATEGORIA>();
            this.SIEDU_EVAL_PREGUNTA = new HashSet<SIEDU_EVAL_PREGUNTA>();
        }
    
        public int EVAL_EVAL { get; set; }
        public int EVAL_PAE { get; set; }
        public string EVAL_DESCRI { get; set; }
        public int EVAL_EVEN { get; set; }
        public short EVAL_DOM_PROCE { get; set; }
        public short EVAL_DOM_MODAL { get; set; }
        public byte EVAL_NRO_PREG { get; set; }
        public System.DateTime EVAL_FECHA { get; set; }
        public string EVAL_ESTADO { get; set; }
        public string EVAL_APLICADA { get; set; }
        public string EVAL_USU_CREA { get; set; }
        public System.DateTime EVAL_FECHA_CREA { get; set; }
        public string EVAL_MAQUINA_CREA { get; set; }
        public string EVAL_IP_CREA { get; set; }
        public string EVAL_USU_MOD { get; set; }
        public Nullable<System.DateTime> EVAL_FECHA_MOD { get; set; }
        public string EVAL_MAQUINA_MOD { get; set; }
        public string EVAL_IP_MOD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIEDU_EVENTO_ESCUELA> SIEDU_EVENTO_ESCUELA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIEDU_EVAL_CATEGORIA> SIEDU_EVAL_CATEGORIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIEDU_EVAL_PREGUNTA> SIEDU_EVAL_PREGUNTA { get; set; }
    }
}
