//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGAC.Layers.Bussiness.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIEDU_PREGUNTA
    {
        public int PREG_PREG { get; set; }
        public short PREG_DOM_TIPO { get; set; }
        public string PREG_DESCRI { get; set; }
        public string PREG_USU_CREA { get; set; }
        public System.DateTime PREG_FECHA_CREA { get; set; }
        public string PREG_MAQUINA_CREA { get; set; }
        public string PREG_IP_CREA { get; set; }
        public string PREG_USU_MOD { get; set; }
        public Nullable<System.DateTime> PREG_FECHA_MOD { get; set; }
        public string PREG_MAQUINA_MOD { get; set; }
        public string PREG_IP_MOD { get; set; }
    }
}
