//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGAC.Layers.Bussiness.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIEDU_AUDITORIA
    {
        public int AUDI_AUDI { get; set; }
        public System.DateTime AUDI_FECHA { get; set; }
        public string AUDI_TABLA { get; set; }
        public string AUDI_OPER { get; set; }
        public string AUDI_REGANTES { get; set; }
        public string AUDI_REGDESPUES { get; set; }
        public string AUDI_USUARIO { get; set; }
        public string AUDI_MAQUINA { get; set; }
        public string AUDI_IP { get; set; }
    }
}
