//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGAC.Layers.Bussiness.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIEDU_INASISTE_EVENTO
    {
        public int INAE_INAE { get; set; }
        public int INAE_PARE { get; set; }
        public System.DateTime INAE_FECHA { get; set; }
        public Nullable<byte> INAE_TIEMPO { get; set; }
        public string INAE_USU_CREA { get; set; }
        public System.DateTime INAE_FECHA_CREA { get; set; }
        public string INAE_MAQUINA_CREA { get; set; }
        public string INAE_IP_CREA { get; set; }
        public string INAE_USU_MOD { get; set; }
        public Nullable<System.DateTime> INAE_FECHA_MOD { get; set; }
        public string INAE_MAQUINA_MOD { get; set; }
        public string INAE_IP_MOD { get; set; }
    }
}
