//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGAC.Layers.Bussiness.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIEDU_PARTICIPANTE_EVENTO
    {
        public int PARE_PARE { get; set; }
        public int PARE_EVEE { get; set; }
        public int PARE_PERS { get; set; }
        public string PARE_ESTADO { get; set; }
        public byte PARE_EDAD { get; set; }
        public string PARE_CUMPLE_PERFIL { get; set; }
        public byte PARE_TIEMPO_SERVICIO { get; set; }
        public bool PARE_UDE_FUERZA { get; set; }
        public decimal PARE_UDE_UDEPE { get; set; }
        public decimal PARE_CARGO { get; set; }
        public int PARE_GRADOS_NUMERICO { get; set; }
        public int PARE_GRADOS_ID_CATEGORIA { get; set; }
        public string PARE_USU_CREA { get; set; }
        public System.DateTime PARE_FECHA_CREA { get; set; }
        public string PARE_MAQUINA_CREA { get; set; }
        public string PARE_IP_CREA { get; set; }
        public string PARE_USU_MOD { get; set; }
        public Nullable<System.DateTime> PARE_FECHA_MOD { get; set; }
        public string PARE_MAQUINA_MOD { get; set; }
        public string PARE_IP_MOD { get; set; }
    }
}
