//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGAC.Layers.Bussiness.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIEDU_EMPLEADO_EXTERNO
    {
        public int EMPE_EMPE { get; set; }
        public string EMPE_TIPOID { get; set; }
        public string EMPE_NROID { get; set; }
        public bool EMPE_UDE_FUERZA { get; set; }
        public decimal EMPE_UDE_UDEPE { get; set; }
        public string EMPE_NOMBRES { get; set; }
        public string EMPE_APELLIDOS { get; set; }
        public System.DateTime EMPE_FECHA_NAC { get; set; }
        public string EMPE_GRUPO_SANG { get; set; }
        public string EMPE_FACTORRH { get; set; }
        public string EMPE_ESTADO_CIVIL { get; set; }
        public string EMPE_SEXO { get; set; }
        public string EMPE_BARRIO_RES { get; set; }
        public string EMPE_DIRE_RES { get; set; }
        public string EMPE_ENTIDAD { get; set; }
        public int EMPE_LUGGEO_PAINAC { get; set; }
        public int EMPE_LUGGEO_CIUNAC { get; set; }
        public int EMPE_LUGGEO_PAIRES { get; set; }
        public int EMPE_LUGGEO_CIURES { get; set; }
        public string EMPE_USU_CREA { get; set; }
        public System.DateTime EMPE_FECHA_CREA { get; set; }
        public string EMPE_MAQUINA_CREA { get; set; }
        public string EMPE_IP_CREA { get; set; }
        public string EMPE_USU_MOD { get; set; }
        public Nullable<System.DateTime> EMPE_FECHA_MOD { get; set; }
        public string EMPE_MAQUINA_MOD { get; set; }
        public string EMPE_IP_MOD { get; set; }
    }
}
