//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGAC.Layers.Bussiness.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIEDU_NECESIDAD
    {
        public int NECE_NECE { get; set; }
        public int NECE_PAE { get; set; }
        public bool NECE_UDE_FUERZA_REGION { get; set; }
        public int NECE_UDE_REGION { get; set; }
        public bool NECE_UDE_FUERZA_UFISI { get; set; }
        public int NECE_UDE_UFISI { get; set; }
        public bool NECE_UDE_FUERZA_UDEPE { get; set; }
        public int NECE_UDE_UDEPE { get; set; }
        public bool NECE_FUERZA_CARRERA { get; set; }
        public int NECE_ID_CARRERA { get; set; }
        public int NECE_NRO { get; set; }
        public string NECE_ESTADO { get; set; }
        public Nullable<short> NECE_DOM_PROCE { get; set; }
        public Nullable<short> NECE_DOM_ESTRA { get; set; }
        public string NECE_ORIGEN { get; set; }
        public short NECE_NOVE { get; set; }
        public string NECE_USU_CREA { get; set; }
        public System.DateTime NECE_FECHA_CREA { get; set; }
        public string NECE_MAQUINA_CREA { get; set; }
        public string NECE_IP_CREA { get; set; }
        public string NECE_USU_MOD { get; set; }
        public Nullable<System.DateTime> NECE_FECHA_MOD { get; set; }
        public string NECE_MAQUINA_MOD { get; set; }
        public string NECE_IP_MOD { get; set; }
    }
}
