//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGAC.Layers.Bussiness.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIGAC_UNIDADES_DEPENDENCIA
    {
        public bool FUERZA { get; set; }
        public decimal CONSECUTIVO { get; set; }
        public string DESCRIPCION_DEPENDENCIA { get; set; }
        public string VIGENTE { get; set; }
        public Nullable<decimal> ORDENAMIENTO { get; set; }
        public Nullable<decimal> NIT { get; set; }
        public string DIRECCION { get; set; }
        public string EMAIL { get; set; }
        public string ORDEN_PUBLICO { get; set; }
        public string PRIMA_CLIMA { get; set; }
        public string PARTIDA_DE_ALIMENTACION { get; set; }
        public string NOMINA { get; set; }
        public string INDICATIVO_MICROONDAS { get; set; }
        public Nullable<System.DateTime> FECHA_ACTIVACION { get; set; }
        public Nullable<System.DateTime> FECHA_DESACTIVACION { get; set; }
        public Nullable<decimal> ID_SIGLA { get; set; }
        public decimal TIUN_CODIGO { get; set; }
        public Nullable<decimal> DEPE_CODIGO { get; set; }
        public Nullable<decimal> DEPE_CODIGO_PERTENECE { get; set; }
        public Nullable<decimal> DEPE_CODIGO_CORRESPONDER { get; set; }
        public Nullable<decimal> EMPL_UNDE_CONSECUTIVO { get; set; }
        public Nullable<bool> EMPL_UNDE_FUERZA { get; set; }
        public Nullable<decimal> EMPL_CONSECUTIVO { get; set; }
        public Nullable<decimal> REGI_CODIGO { get; set; }
        public Nullable<decimal> BARRI_CODIGO { get; set; }
        public Nullable<int> BARRI_LUGE_CODIGO { get; set; }
        public Nullable<int> LUGE_CODIGO { get; set; }
        public Nullable<bool> GUCO_FUERZA { get; set; }
        public Nullable<decimal> GUCO_CODIGO { get; set; }
        public Nullable<bool> UNDE_FUERZA { get; set; }
        public Nullable<decimal> UNDE_CONSECUTIVO { get; set; }
        public string CREADO_POR { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string MAQUINA_CREACION { get; set; }
        public string ACTUALIZADO_POR { get; set; }
        public Nullable<System.DateTime> FECHA_ACTUALIZA { get; set; }
        public string MAQUINA_ACTUALIZA { get; set; }
        public Nullable<byte> DIFICULTAD { get; set; }
        public string TIPO_PAGO { get; set; }
        public string SIGLA_PAPA { get; set; }
        public Nullable<decimal> CODIGO_DELEGACION { get; set; }
        public Nullable<decimal> NIVEL_RIESGO { get; set; }
        public Nullable<byte> CONDICION_PARTIDA_ALIMENTACION { get; set; }
        public Nullable<int> TELEFONO { get; set; }
        public string CATEGORIA_UNIDAD { get; set; }
        public string CENTRO_DE_COSTOS { get; set; }
        public string PRIMA_CARABINERO { get; set; }
        public string SIGLA_DEPENDE { get; set; }
        public string SIGLA_FISICA { get; set; }
        public string SUBMARINISTA { get; set; }
        public string ZONA_CRITICA { get; set; }
        public Nullable<decimal> TIPO_DOTACION { get; set; }
        public string SIGLA_SIVICC { get; set; }
        public string ORDENADO { get; set; }
        public string CODIGO { get; set; }
        public string COD_MIGRACION { get; set; }
        public string REG_VALIDADO { get; set; }
        public string REG_ACT_POR { get; set; }
        public Nullable<System.DateTime> REG_FECHA_ACT { get; set; }
        public string REG_MAQUINA_ACT { get; set; }
        public string AREA { get; set; }
    }
}
