//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGAC.Layers.Bussiness.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIGAC_CURSOS
    {
        public decimal ID_CURSO { get; set; }
        public System.DateTime FECHA { get; set; }
        public string DESCRIPCION { get; set; }
        public string RAMA_PROFESIONAL { get; set; }
        public Nullable<decimal> TIPO { get; set; }
        public string VIGENTE { get; set; }
    }
}
