//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGAC.Layers.Bussiness.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIGAC_CARRERAS
    {
        public decimal ID_CARRERA { get; set; }
        public bool FUERZA { get; set; }
        public decimal ID_NIVEL_ACADEMICO { get; set; }
        public string DESCRIPCION { get; set; }
        public string CLASE_EDUCACION { get; set; }
        public string TIPO_PROGRAMA { get; set; }
        public string TITULO { get; set; }
        public string OBSERVACION { get; set; }
        public string ABREVIATURA { get; set; }
        public string CREADO_POR { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string MAQUINA_CREACION { get; set; }
        public string ACTUALIZADO_POR { get; set; }
        public Nullable<System.DateTime> FECHA_ACTUALIZA { get; set; }
        public string MAQUINA_ACTUALIZA { get; set; }
        public string VIGENTE { get; set; }
        public string REG_VALIDADO { get; set; }
        public string REG_ACT_POR { get; set; }
        public Nullable<System.DateTime> REG_FECHA_ACT { get; set; }
        public string REG_MAQUINA_ACT { get; set; }
    }
}
