//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGAC.Layers.Bussiness.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIGAC_GRADOS
    {
        public decimal ID_GRADO { get; set; }
        public bool FUERZA { get; set; }
        public string ALFABETICO { get; set; }
        public short NUMERICO { get; set; }
        public string NATURALEZA { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<byte> ESCALA { get; set; }
        public Nullable<decimal> SUELDO { get; set; }
        public Nullable<int> PLANTA_ACTUAL { get; set; }
        public Nullable<int> PLANTA_AUTORIZADA { get; set; }
        public Nullable<int> PLANTA_IDEAL { get; set; }
        public Nullable<short> DESCUENTO_COMISION_EXTERIOR { get; set; }
        public Nullable<byte> TIEMPO_GRADO { get; set; }
        public decimal ID_CATEGORIA { get; set; }
        public Nullable<decimal> ID_TIPO_CATEGORIA { get; set; }
        public string MAQUINA_CREACION { get; set; }
        public string MAQUINA_ACTUALIZA { get; set; }
        public Nullable<decimal> FUNCION_PUBLICA { get; set; }
        public string VIGENTE { get; set; }
        public Nullable<decimal> PORCENTAJE_INCREMENTO { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
        public Nullable<decimal> RACION_ALIMENTICIA { get; set; }
        public string REG_VALIDADO { get; set; }
        public string REG_ACT_POR { get; set; }
        public Nullable<System.DateTime> REG_FECHA_ACT { get; set; }
        public string REG_MAQUINA_ACT { get; set; }
    }
}
