//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGAC.Layers.Bussiness.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIGAC_LUGARES_GEOGRAFICOS
    {
        public int CODIGO { get; set; }
        public string DESCRIPCION { get; set; }
        public string ABREVIATURA { get; set; }
        public string TIPO { get; set; }
        public string INDICATIVO_TELEFONICO { get; set; }
        public string EXTERIOR { get; set; }
        public string ZONA { get; set; }
        public string CODIGO_DANE { get; set; }
        public string CODIGO_REGISTRADURIA { get; set; }
        public Nullable<int> LUGE_PAPA { get; set; }
        public Nullable<int> LUGE_CODIGO { get; set; }
        public string CREADO_POR { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string MAQUINA_CREACION { get; set; }
        public string ACTUALIZADO_POR { get; set; }
        public Nullable<System.DateTime> FECHA_ACTUALIZA { get; set; }
        public string MAQUINA_ACTUALIZA { get; set; }
        public Nullable<decimal> ORIG_SYSTEM_REF { get; set; }
        public string CODI_PROVINCIA { get; set; }
        public string CODI_CIPIO { get; set; }
        public string REG_VALIDADO { get; set; }
        public string REG_ACT_POR { get; set; }
        public Nullable<System.DateTime> REG_FECHA_ACT { get; set; }
        public string REG_MAQUINA_ACT { get; set; }
    }
}
