//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGAC.Layers.Bussiness.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIGAC_CURSOS_EMPLEADOS
    {
        public decimal CURSOS_EMPLEADOS_ID { get; set; }
        public decimal EMPL_CONSECUTIVO { get; set; }
        public decimal EMPL_UNDE_FUERZA { get; set; }
        public decimal ID_CURSO { get; set; }
        public Nullable<decimal> ID_CENTRO_EDUCATIVO { get; set; }
        public Nullable<System.DateTime> FECHA_INICIO { get; set; }
        public Nullable<System.DateTime> FECHA_FIN { get; set; }
        public Nullable<decimal> DURACION { get; set; }
        public Nullable<decimal> DURACION_TIPO { get; set; }
        public string OBSERVACION { get; set; }
        public string USUARIO_CREACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string MAQUINA_CREACION { get; set; }
        public Nullable<decimal> ID_TIPO { get; set; }
        public Nullable<decimal> EMPL_UNDE_CONSECUTIVO { get; set; }
        public string TARJETA_PROFESIONAL { get; set; }
        public Nullable<System.DateTime> FECHA_GRADO { get; set; }
        public Nullable<decimal> PUESTO { get; set; }
        public string TITULO { get; set; }
        public string USUARIO_MODIFICA { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICA { get; set; }
        public string MAQUINA_MODIFICA { get; set; }
        public string CARRERA_PRINCIPAL { get; set; }
        public string MOTIVO_OPERACION { get; set; }
        public string REG_VALIDADO { get; set; }
        public string REG_ACT_POR { get; set; }
        public Nullable<System.DateTime> REG_FECHA_ACT { get; set; }
        public string REG_MAQUINA_ACT { get; set; }
    }
}
