//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGAC.Layers.Bussiness.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIGAC_EMPLEADOS
    {
        public decimal CONSECUTIVO { get; set; }
        public bool UNDE_FUERZA { get; set; }
        public decimal UNDE_CONSECUTIVO { get; set; }
        public string TIPO_IDENTIFICACION { get; set; }
        public string IDENTIFICACION { get; set; }
        public Nullable<decimal> CODIGO_MILITAR { get; set; }
        public string NOMBRES { get; set; }
        public string APELLIDOS { get; set; }
        public System.DateTime FECHA_NACIMIENTO { get; set; }
        public string GRUPO_SANGUINEO { get; set; }
        public string FACTOR_RH { get; set; }
        public string ESTADO_CIVIL { get; set; }
        public string SEXO { get; set; }
        public string DIRECCION { get; set; }
        public string TELEFONO { get; set; }
        public string CLASE_LIBRETA { get; set; }
        public string TIPO_EMPLEADO { get; set; }
        public string ESTADO_EMPLEADO { get; set; }
        public string ACTIVO { get; set; }
        public Nullable<byte> DIAS_VACACIONES { get; set; }
        public Nullable<System.DateTime> FECHA_VACACIONES { get; set; }
        public Nullable<int> PLACA { get; set; }
        public string HOJA_VIDA { get; set; }
        public Nullable<decimal> NUMERO_CARNE { get; set; }
        public Nullable<decimal> HORAS_LABORADAS { get; set; }
        public Nullable<byte> NUMERO_CURSO { get; set; }
        public Nullable<decimal> UBICACION_ESCALAFON { get; set; }
        public string ENCARGO { get; set; }
        public string CARRERA_ADTVA { get; set; }
        public string LEY_100 { get; set; }
        public string JUSTICIA_PENAL { get; set; }
        public string RESERVA { get; set; }
        public string CONDICION_SANIDAD { get; set; }
        public string CLASE_NOMINA { get; set; }
        public Nullable<System.DateTime> FECHA_DEFUNCION { get; set; }
        public string VALIDA_ARCO { get; set; }
        public decimal ID_GRADO { get; set; }
        public Nullable<int> LUGE_CODIGO_NACE { get; set; }
        public Nullable<int> LUGE_CODIGO_LABORA { get; set; }
        public Nullable<decimal> LUBA_BARRI_CODIGO { get; set; }
        public Nullable<int> LUGE_CODIGO_RESIDE { get; set; }
        public decimal CARG_CARGO { get; set; }
        public bool CARG_FUERZA { get; set; }
        public Nullable<bool> EMPR_UNDE_FUERZA { get; set; }
        public Nullable<decimal> EMPR_UNDE_CONSECUTIVO { get; set; }
        public Nullable<long> EMPR_IDENTIFICACION { get; set; }
        public string EMPR_TIPO_IDENTIFICACION { get; set; }
        public Nullable<bool> UNDE_FUERZA_ATENDIDO { get; set; }
        public Nullable<decimal> UNDE_CONSECUTIVO_ATENDIDO { get; set; }
        public Nullable<decimal> UNDE_CONSECUTIVO_NOMINADO { get; set; }
        public bool UNDE_FUERZA_LABORANDO { get; set; }
        public decimal UNDE_CONSECUTIVO_LABORANDO { get; set; }
        public Nullable<bool> ARCU_FUERZA { get; set; }
        public Nullable<byte> ARCU_ID_ARMA_CUERPO { get; set; }
        public Nullable<bool> ESPE_FUERZA { get; set; }
        public Nullable<decimal> ESPE_ID_ESPECIALIDAD { get; set; }
        public Nullable<bool> CARR_FUERZA { get; set; }
        public Nullable<int> CARRE_ID_CARRERA { get; set; }
        public string CREADO_POR { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string MAQUINA_CREACION { get; set; }
        public string ACTUALIZADO_POR { get; set; }
        public Nullable<System.DateTime> FECHA_ACTUALIZA { get; set; }
        public string MAQUINA_ACTUALIZA { get; set; }
        public decimal SILA_ID_SITUAC_LABOR { get; set; }
        public string CENTRO_SOCIAL { get; set; }
        public string CENTRO_VACACIONAL { get; set; }
        public string EDIFICIO { get; set; }
        public string SIGLA_LABORANDO { get; set; }
        public string CONDICION_OFITE { get; set; }
        public string LIBRETA_MILITAR { get; set; }
        public string DRAGONEANTE { get; set; }
        public string DESIGNADO { get; set; }
        public string REGISTRO_DUPLICADO { get; set; }
        public string MIGRADO_ORDEN { get; set; }
        public string ID_FUENTE { get; set; }
        public string ID_NOMINA { get; set; }
        public Nullable<int> CON_NIVEL { get; set; }
        public string USUARIO_EMPRESARIAL { get; set; }
        public Nullable<System.DateTime> FECHA_EXPEDICION_LIBRETA { get; set; }
        public Nullable<decimal> UNRE_CONSECUTIVO { get; set; }
        public Nullable<decimal> REGISTRO_DEFUNCION { get; set; }
        public Nullable<System.DateTime> FECHA_PRESUNCION { get; set; }
        public string CLASE_PRESUNCION { get; set; }
        public string AUDIOCONSULTA_PIN { get; set; }
        public Nullable<bool> CHEQUEO_PIN { get; set; }
        public Nullable<bool> RESPUESTA_PIN { get; set; }
        public string CORREO_ELECTRONICO { get; set; }
        public Nullable<decimal> PLACA_CHIP { get; set; }
        public string MOTIVO_OPERACION { get; set; }
        public string NUMERO_CELULAR { get; set; }
        public Nullable<decimal> LICENCIAC_TIPO { get; set; }
        public string LICENCIAC_NUMERO { get; set; }
        public Nullable<decimal> COLOR_PIEL { get; set; }
        public Nullable<decimal> COLOR_CABELLO { get; set; }
        public Nullable<decimal> COLOR_OJOS { get; set; }
        public Nullable<decimal> ESTATURA { get; set; }
        public Nullable<short> UNIDAD_PAGO_NOMINA { get; set; }
        public Nullable<short> ID_DIRECCION_PERTENECE { get; set; }
        public Nullable<short> ID_DEPARTAMENTO_PERTENECE { get; set; }
        public Nullable<short> ID_SUPERVISORIA_PERTENECE { get; set; }
        public Nullable<short> ID_DEPENDIENTE_PERTENECE { get; set; }
        public string REG_VALIDADO { get; set; }
        public string REG_ACT_POR { get; set; }
        public Nullable<System.DateTime> REG_FECHA_ACT { get; set; }
        public string REG_MAQUINA_ACT { get; set; }
        public Nullable<decimal> ID_ESTRUCTURA_ORGANIZACIONAL { get; set; }
        public Nullable<decimal> CEJAS { get; set; }
        public Nullable<decimal> DENTADURA { get; set; }
        public Nullable<decimal> NARIZ { get; set; }
        public Nullable<decimal> PESO { get; set; }
        public string RECOMENDADO { get; set; }
        public string SENAPARTICULAR { get; set; }
        public Nullable<decimal> CORREA { get; set; }
        public Nullable<decimal> PANTALON { get; set; }
        public string CAMISA { get; set; }
        public Nullable<decimal> CALZADOS { get; set; }
        public string TELEFONO2 { get; set; }
        public string CELULAR1 { get; set; }
        public string CELULAR2 { get; set; }
        public string CENSO_PROVINCIA { get; set; }
        public string CENSO_MUNICIPIO { get; set; }
        public string CENSO_DISTRITO_MUNICIPAL { get; set; }
        public string CENSO_BARRIO_SECTOR { get; set; }
        public string CENSO_COMENTARIO { get; set; }
        public string CENSO_DATOS_ARMA { get; set; }
        public string MOTIVO { get; set; }
        public string CORREO_ELECTRONICOP { get; set; }
    }
}
