//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGAC.Layers.Bussiness.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPOS_ASIGNATURA
    {
        public decimal ID { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<decimal> CAMPO1 { get; set; }
        public Nullable<decimal> CAMPO2 { get; set; }
        public Nullable<decimal> CAMPO3 { get; set; }
        public string CAMPO4 { get; set; }
        public decimal ESTATUS { get; set; }
    }
}
