//$(document).ready(function () {
//    $("select").searchable({
//        maxListSize: 100,                       // if list size are less than maxListSize, show them all
//        maxMultiMatch: 50,                      // how many matching entries should be displayed
//        exactMatch: false,                      // Exact matching on search
//        wildcards: true,                        // Support for wildcard characters (*, ?)
//        ignoreCase: true,                       // Ignore case sensitivity
//        latency: 200,                           // how many millis to wait until starting search
//        warnMultiMatch: '{0} entradas encontradas ...',  // string to append to a list of entries cut short by maxMultiMatch
//        warnNoMatch: 'No entradas encontradas ...'     // string to show in the list when no entries match  //zIndex: 'auto' // zIndex for elements generated by this plugin
//    });
//});


//SELECT 2 FRAMEWORK


//$(document).ready(function () {
//    $('Jquery_Select2').select2({
//        placeholder: 'Seleccione una opcion',
//        maximun
//    });
//});


//$('Jquery_Select2_Modal').select2({
//    dropdownParent: $('#myModal')
//});